platform :ios, '15.0'
use_modular_headers!

target 'iosApp' do
  pod 'shared', :path => '../shared'
  pod 'Google-Mobile-Ads-SDK'
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
    end
  end
end
