package com.valoser.futacha.shared.ui.board

import com.valoser.futacha.shared.model.CatalogNavEntryConfig
import com.valoser.futacha.shared.model.Post
import com.valoser.futacha.shared.model.ThreadHistoryEntry
import com.valoser.futacha.shared.model.ThreadMenuEntryConfig
import com.valoser.futacha.shared.model.ThreadMenuEntryId
import com.valoser.futacha.shared.repo.BoardRepository
import com.valoser.futacha.shared.util.SaveDirectorySelection
import kotlinx.coroutines.CoroutineScope

internal data class ThreadScreenInteractionUiAggregateBundle(
    val mediaBindings: ThreadScreenMediaBindings,
    val controllerBindings: ThreadScreenControllerBindingsBundle,
    val uiBindings: ThreadScreenUiBindingsBundle
)

internal fun buildThreadScreenInteractionUiAggregateBundle(
    currentPreviewState: () -> ThreadMediaPreviewState,
    setPreviewState: (ThreadMediaPreviewState) -> Unit,
    currentMediaEntries: () -> List<MediaPreviewEntry>,
    coroutineScope: CoroutineScope,
    currentActionInProgress: () -> Boolean,
    setActionInProgress: (Boolean) -> Unit,
    currentLastBusyNoticeAtMillis: () -> Long,
    setLastBusyNoticeAtMillis: (Long) -> Unit,
    busyNoticeIntervalMillis: Long,
    showMessage: (String) -> Unit,
    showOptionalMessage: (String?) -> Unit,
    onActionDebugLog: (String) -> Unit,
    onActionInfoLog: (String) -> Unit,
    onActionErrorLog: (String, Throwable) -> Unit,
    currentIsHistoryRefreshing: () -> Boolean,
    setIsHistoryRefreshing: (Boolean) -> Unit,
    onHistoryRefresh: suspend () -> Unit,
    showHistoryRefreshMessage: suspend (String) -> Unit,
    currentReadAloudState: () -> ThreadReadAloudRuntimeState,
    setReadAloudState: (ThreadReadAloudRuntimeState) -> Unit,
    scrollToReadAloudPostIndex: suspend (Int) -> Unit,
    speakReadAloudText: suspend (String) -> Unit,
    cancelActiveReadAloud: () -> Unit,
    currentReadAloudSegments: () -> List<ReadAloudSegment>,
    isRefreshing: () -> Boolean,
    onOpenReplyDialog: () -> Unit,
    onScrollTop: () -> Unit,
    onScrollBottom: () -> Unit,
    onShowRefreshBusyMessage: () -> Unit,
    onStartRefreshFromMenu: () -> Unit,
    onOpenGallery: () -> Unit,
    onDelegateToSaveHandler: () -> Unit,
    onShowFilterSheet: () -> Unit,
    onShowSettingsSheet: () -> Unit,
    onClearNgHeaderPrefill: () -> Unit,
    onShowNgManagement: () -> Unit,
    onOpenExternalApp: () -> Unit,
    onShowReadAloudControls: () -> Unit,
    onTogglePrivacy: () -> Unit,
    currentSearchIndex: () -> Int,
    setCurrentSearchIndex: (Int) -> Unit,
    currentSearchMatches: () -> List<ThreadSearchMatch>,
    onScrollToSearchMatchPostIndex: (Int?) -> Unit,
    onCloseDrawerAfterHistorySelection: () -> Unit,
    onHistoryEntrySelected: (ThreadHistoryEntry) -> Unit,
    currentOverlayState: () -> ThreadPostOverlayState,
    setOverlayState: (ThreadPostOverlayState) -> Unit,
    lastUsedDeleteKey: String,
    currentSaidaneLabel: (Post) -> String?,
    isSelfPost: (Post) -> Boolean,
    onSaidaneLabelUpdated: (Post, String) -> Unit,
    repository: BoardRepository,
    effectiveBoardUrl: String,
    threadId: String,
    currentFirstVisibleItemIndex: () -> Int,
    currentFirstVisibleItemOffset: () -> Int,
    onStartRefreshFromPull: (Int, Int) -> Unit,
    onHistoryEntryDismissed: (ThreadHistoryEntry) -> Unit,
    onBoardClick: () -> Unit,
    onHistoryBatchDeleteClick: () -> Unit,
    onHistorySettingsClick: () -> Unit,
    onSearchQueryChange: (String) -> Unit,
    onSearchClose: () -> Unit,
    onBack: () -> Unit,
    onOpenHistory: () -> Unit,
    onSearch: () -> Unit,
    onOpenGlobalSettings: () -> Unit,
    replyDialogBinding: ThreadReplyDialogStateBinding,
    mediaPreviewEntryCount: Int,
    onSavePreviewMedia: (MediaPreviewEntry) -> Unit,
    galleryPosts: List<Post>?,
    onDismissGallery: () -> Unit,
    onScrollToPostIndex: (Int) -> Unit,
    threadFilterBinding: ThreadFilterUiStateBinding,
    onDismissSettingsSheet: () -> Unit,
    onDismissFilterSheet: () -> Unit,
    onApplySettingsActionState: (ThreadSettingsActionState) -> Unit,
    firstVisibleSegmentIndex: () -> Int,
    onPauseReadAloud: () -> Unit,
    onStopReadAloud: () -> Unit,
    onShowReadAloudStoppedMessage: () -> Unit,
    onDismissReadAloudControls: () -> Unit,
    onDismissNgManagement: () -> Unit,
    ngMutationCallbacks: ThreadNgMutationCallbacks,
    onDismissSaveProgress: () -> Unit,
    onCancelSaveProgress: () -> Unit,
    onDismissGlobalSettings: () -> Unit,
    onBackgroundRefreshChanged: (Boolean) -> Unit,
    onLightweightModeChanged: (Boolean) -> Unit,
    onManualSaveDirectoryChanged: (String) -> Unit,
    onSaveDirectorySelectionChanged: (SaveDirectorySelection) -> Unit,
    onOpenSaveDirectoryPicker: (() -> Unit)?,
    onOpenCookieManager: (() -> Unit)?,
    onFileManagerSelected: ((packageName: String, label: String) -> Unit)?,
    onClearPreferredFileManager: (() -> Unit)?,
    onThreadMenuEntriesChanged: (List<ThreadMenuEntryConfig>) -> Unit,
    onCatalogNavEntriesChanged: (List<CatalogNavEntryConfig>) -> Unit,
    onDismissCookieManagement: () -> Unit
): ThreadScreenInteractionUiAggregateBundle {
    val mediaBindings = buildThreadScreenMediaBindings(
        currentPreviewState = currentPreviewState,
        setPreviewState = setPreviewState,
        currentEntries = currentMediaEntries
    )
    val controllerBindings = buildThreadScreenControllerBindingsBundle(
        coroutineScope = coroutineScope,
        currentActionInProgress = currentActionInProgress,
        setActionInProgress = setActionInProgress,
        currentLastBusyNoticeAtMillis = currentLastBusyNoticeAtMillis,
        setLastBusyNoticeAtMillis = setLastBusyNoticeAtMillis,
        busyNoticeIntervalMillis = busyNoticeIntervalMillis,
        showMessage = showMessage,
        showOptionalMessage = showOptionalMessage,
        onActionDebugLog = onActionDebugLog,
        onActionInfoLog = onActionInfoLog,
        onActionErrorLog = onActionErrorLog,
        currentIsHistoryRefreshing = currentIsHistoryRefreshing,
        setIsHistoryRefreshing = setIsHistoryRefreshing,
        onHistoryRefresh = onHistoryRefresh,
        showHistoryRefreshMessage = showHistoryRefreshMessage,
        currentReadAloudState = currentReadAloudState,
        setReadAloudState = setReadAloudState,
        scrollToReadAloudPostIndex = scrollToReadAloudPostIndex,
        speakReadAloudText = speakReadAloudText,
        cancelActiveReadAloud = cancelActiveReadAloud,
        currentReadAloudSegments = currentReadAloudSegments,
        isRefreshing = isRefreshing,
        onOpenReplyDialog = onOpenReplyDialog,
        onScrollTop = onScrollTop,
        onScrollBottom = onScrollBottom,
        onShowRefreshBusyMessage = onShowRefreshBusyMessage,
        onStartRefreshFromMenu = onStartRefreshFromMenu,
        onOpenGallery = onOpenGallery,
        onDelegateToSaveHandler = onDelegateToSaveHandler,
        onShowFilterSheet = onShowFilterSheet,
        onShowSettingsSheet = onShowSettingsSheet,
        onClearNgHeaderPrefill = onClearNgHeaderPrefill,
        onShowNgManagement = onShowNgManagement,
        onOpenExternalApp = onOpenExternalApp,
        onShowReadAloudControls = onShowReadAloudControls,
        onTogglePrivacy = onTogglePrivacy,
        currentSearchIndex = currentSearchIndex,
        setCurrentSearchIndex = setCurrentSearchIndex,
        currentSearchMatches = currentSearchMatches,
        onScrollToSearchMatchPostIndex = onScrollToSearchMatchPostIndex,
        onCloseDrawerAfterHistorySelection = onCloseDrawerAfterHistorySelection,
        onHistoryEntrySelected = onHistoryEntrySelected,
        currentOverlayState = currentOverlayState,
        setOverlayState = setOverlayState,
        lastUsedDeleteKey = lastUsedDeleteKey,
        currentSaidaneLabel = currentSaidaneLabel,
        isSelfPost = isSelfPost,
        onSaidaneLabelUpdated = onSaidaneLabelUpdated,
        repository = repository,
        effectiveBoardUrl = effectiveBoardUrl,
        threadId = threadId,
        currentFirstVisibleItemIndex = currentFirstVisibleItemIndex,
        currentFirstVisibleItemOffset = currentFirstVisibleItemOffset,
        onStartRefreshFromPull = onStartRefreshFromPull,
        onHistoryEntryDismissed = onHistoryEntryDismissed,
        onBoardClick = onBoardClick,
        onHistoryBatchDeleteClick = onHistoryBatchDeleteClick,
        onHistorySettingsClick = onHistorySettingsClick
    )
    val interactionBindings = controllerBindings.interactionBindings
    val readAloudBindings = controllerBindings.actionExecutionBindings.readAloudBindings
    return ThreadScreenInteractionUiAggregateBundle(
        mediaBindings = mediaBindings,
        controllerBindings = controllerBindings,
        uiBindings = buildThreadScreenUiBindingsBundle(
            searchNavigationCallbacks = interactionBindings.searchNavigationCallbacks,
            onSearchQueryChange = onSearchQueryChange,
            onSearchClose = onSearchClose,
            onBack = onBack,
            onOpenHistory = onOpenHistory,
            onSearch = onSearch,
            onOpenGlobalSettings = onOpenGlobalSettings,
            onAction = interactionBindings.menuEntryHandler,
            replyDialogBinding = replyDialogBinding,
            currentPostOverlayState = currentOverlayState,
            setPostOverlayState = setOverlayState,
            mediaPreviewState = currentPreviewState,
            setMediaPreviewState = setPreviewState,
            mediaPreviewEntryCount = mediaPreviewEntryCount,
            onSavePreviewMedia = onSavePreviewMedia,
            galleryPosts = galleryPosts,
            onDismissGallery = onDismissGallery,
            onScrollToPostIndex = onScrollToPostIndex,
            threadFilterBinding = threadFilterBinding,
            onDismissSettingsSheet = onDismissSettingsSheet,
            onDismissFilterSheet = onDismissFilterSheet,
            onApplySettingsActionState = onApplySettingsActionState,
            onOpenNgManagement = onShowNgManagement,
            onOpenExternalApp = onOpenExternalApp,
            onTogglePrivacy = onTogglePrivacy,
            firstVisibleSegmentIndex = firstVisibleSegmentIndex,
            onSeekToReadAloudIndex = readAloudBindings.seekReadAloudToIndex,
            onPlayReadAloud = readAloudBindings.startReadAloud,
            onPauseReadAloud = onPauseReadAloud,
            onStopReadAloud = onStopReadAloud,
            onShowReadAloudStoppedMessage = onShowReadAloudStoppedMessage,
            onDismissReadAloudControls = onDismissReadAloudControls,
            onDismissNgManagement = onDismissNgManagement,
            ngMutationCallbacks = ngMutationCallbacks,
            onDismissSaveProgress = onDismissSaveProgress,
            onCancelSaveProgress = onCancelSaveProgress,
            onDismissGlobalSettings = onDismissGlobalSettings,
            onBackgroundRefreshChanged = onBackgroundRefreshChanged,
            onLightweightModeChanged = onLightweightModeChanged,
            onManualSaveDirectoryChanged = onManualSaveDirectoryChanged,
            onSaveDirectorySelectionChanged = onSaveDirectorySelectionChanged,
            onOpenSaveDirectoryPicker = onOpenSaveDirectoryPicker,
            onOpenCookieManager = onOpenCookieManager,
            onFileManagerSelected = onFileManagerSelected,
            onClearPreferredFileManager = onClearPreferredFileManager,
            onThreadMenuEntriesChanged = onThreadMenuEntriesChanged,
            onCatalogNavEntriesChanged = onCatalogNavEntriesChanged,
            onDismissCookieManagement = onDismissCookieManagement
        )
    )
}
