-- Futacha compatibility database schema export, version 9.
CREATE TABLE compat_metadata(key TEXT PRIMARY KEY NOT NULL, value TEXT NOT NULL);
CREATE TABLE compat_board(board_key TEXT PRIMARY KEY NOT NULL, name TEXT NOT NULL, canonical_url TEXT UNIQUE NOT NULL, original_url TEXT NOT NULL, sort_order INTEGER NOT NULL);
CREATE TABLE compat_workspace(singleton_id INTEGER PRIMARY KEY CHECK(singleton_id=1), active_tab_key TEXT, catalog_host_board_key TEXT, main_selector_open INTEGER NOT NULL DEFAULT 0, catalog_selector_open INTEGER NOT NULL DEFAULT 0, thread_selector_open INTEGER NOT NULL DEFAULT 0, selector_presentation TEXT NOT NULL, generation INTEGER NOT NULL DEFAULT 0);
CREATE TABLE compat_tab(tab_key TEXT PRIMARY KEY NOT NULL, canonical_url TEXT UNIQUE NOT NULL, original_url TEXT NOT NULL, board_key TEXT NOT NULL, board_name TEXT NOT NULL, thread_no TEXT NOT NULL, title TEXT NOT NULL, thumbnail_url TEXT, reply_count INTEGER NOT NULL, checked_reply_count INTEGER NOT NULL, is_dead INTEGER NOT NULL, is_isolated INTEGER NOT NULL, is_exploded INTEGER NOT NULL, is_old INTEGER NOT NULL, favorite INTEGER NOT NULL, inserted_at INTEGER NOT NULL, content_updated_at INTEGER NOT NULL, scroll_anchor_json TEXT NOT NULL, snapshot_revision INTEGER NOT NULL, FOREIGN KEY(board_key) REFERENCES compat_board(board_key) ON DELETE CASCADE);
CREATE INDEX compat_tab_inserted_idx ON compat_tab(inserted_at DESC);
CREATE TABLE compat_reply_draft(tab_key TEXT PRIMARY KEY NOT NULL, name TEXT NOT NULL, email TEXT NOT NULL, subject TEXT NOT NULL, comment TEXT NOT NULL, attachment_uri TEXT, delete_key TEXT NOT NULL, updated_at INTEGER NOT NULL, FOREIGN KEY(tab_key) REFERENCES compat_tab(tab_key) ON DELETE CASCADE);
CREATE TABLE compat_build_draft(board_key TEXT PRIMARY KEY NOT NULL, name TEXT NOT NULL, email TEXT NOT NULL, subject TEXT NOT NULL, comment TEXT NOT NULL, attachment_uri TEXT, delete_key TEXT NOT NULL, updated_at INTEGER NOT NULL, FOREIGN KEY(board_key) REFERENCES compat_board(board_key) ON DELETE CASCADE);
CREATE TABLE compat_history(canonical_url TEXT PRIMARY KEY NOT NULL, original_url TEXT NOT NULL, board_key TEXT NOT NULL, board_name TEXT NOT NULL, thread_no TEXT NOT NULL, title TEXT NOT NULL, thumbnail_url TEXT, reply_count INTEGER NOT NULL, content_updated_at INTEGER NOT NULL, scroll_anchor_json TEXT NOT NULL, FOREIGN KEY(board_key) REFERENCES compat_board(board_key) ON DELETE CASCADE);
CREATE INDEX compat_history_updated_idx ON compat_history(content_updated_at DESC);
CREATE TABLE compat_thread_snapshot(tab_key TEXT PRIMARY KEY NOT NULL, revision INTEGER NOT NULL, fetched_at INTEGER NOT NULL, board_title TEXT, expires_label TEXT, deleted_notice TEXT);
CREATE TABLE compat_post(tab_key TEXT NOT NULL, revision INTEGER NOT NULL, position INTEGER NOT NULL, post_json TEXT NOT NULL, PRIMARY KEY(tab_key, revision, position));
CREATE TABLE compat_catalog_preference(board_key TEXT PRIMARY KEY NOT NULL, sort_mode TEXT NOT NULL, layout_mode TEXT NOT NULL, reply_priority_enabled INTEGER NOT NULL, show_non_priority INTEGER NOT NULL, few_replies_delay INTEGER NOT NULL, FOREIGN KEY(board_key) REFERENCES compat_board(board_key) ON DELETE CASCADE);
CREATE TABLE compat_catalog_snapshot(board_key TEXT NOT NULL, mode TEXT NOT NULL, revision INTEGER NOT NULL, fetched_at INTEGER NOT NULL, PRIMARY KEY(board_key, mode, revision), FOREIGN KEY(board_key) REFERENCES compat_board(board_key) ON DELETE CASCADE);
CREATE TABLE compat_catalog_item(board_key TEXT NOT NULL, mode TEXT NOT NULL, revision INTEGER NOT NULL, position INTEGER NOT NULL, item_json TEXT NOT NULL, PRIMARY KEY(board_key, mode, revision, position), FOREIGN KEY(board_key, mode, revision) REFERENCES compat_catalog_snapshot(board_key, mode, revision) ON DELETE CASCADE);
CREATE TABLE compat_preference(key TEXT PRIMARY KEY NOT NULL, value_json TEXT NOT NULL);
CREATE TABLE compat_toolbar(surface TEXT NOT NULL, command_key TEXT NOT NULL, position INTEGER NOT NULL, active INTEGER NOT NULL, PRIMARY KEY(surface, command_key));
CREATE TABLE compat_ng_rule(rule_id TEXT PRIMARY KEY NOT NULL, kind TEXT NOT NULL, scope_key TEXT, normalized_value TEXT NOT NULL, payload_json TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE compat_watch_rule(rule_id TEXT PRIMARY KEY NOT NULL, board_key TEXT, normalized_value TEXT NOT NULL, display_value TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS compat_closed_batch(batch_id TEXT PRIMARY KEY NOT NULL, expires_at INTEGER NOT NULL, batch_json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS compat_closed_batch_expires_idx ON compat_closed_batch(expires_at DESC);
CREATE TABLE IF NOT EXISTS archive_report_outbox(thread_id TEXT PRIMARY KEY NOT NULL, thread_url TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'pending', first_seen_at INTEGER NOT NULL, next_attempt_at INTEGER NOT NULL, attempt_count INTEGER NOT NULL DEFAULT 0, batch_request_id TEXT, batch_payload_hash TEXT, sending_started_at INTEGER, accepted_at INTEGER, expires_at INTEGER, last_error TEXT);
CREATE INDEX IF NOT EXISTS idx_archive_report_outbox_due ON archive_report_outbox(state, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_archive_report_outbox_batch ON archive_report_outbox(batch_request_id, state);
CREATE INDEX IF NOT EXISTS idx_archive_report_outbox_expiry ON archive_report_outbox(state, expires_at);
CREATE TABLE IF NOT EXISTS compat_catalog_dropped(board_key TEXT NOT NULL, thread_id TEXT NOT NULL, item_json TEXT NOT NULL, dropped_at INTEGER NOT NULL, PRIMARY KEY(board_key, thread_id), FOREIGN KEY(board_key) REFERENCES compat_board(board_key) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS compat_catalog_dropped_recent_idx ON compat_catalog_dropped(board_key, dropped_at DESC, thread_id DESC);
ALTER TABLE compat_catalog_dropped ADD COLUMN last_seen_at INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS compat_catalog_dropped_class_idx ON compat_catalog_dropped(board_key, last_seen_at DESC);
ALTER TABLE compat_catalog_dropped ADD COLUMN drop_class TEXT NOT NULL DEFAULT 'DIE';
ALTER TABLE compat_catalog_dropped ADD COLUMN inserted_at INTEGER NOT NULL DEFAULT 0;
UPDATE compat_catalog_dropped SET last_seen_at=dropped_at, inserted_at=dropped_at WHERE last_seen_at=0 AND inserted_at=0;
CREATE TABLE IF NOT EXISTS compat_history_tombstone(canonical_url TEXT PRIMARY KEY NOT NULL, deleted_at INTEGER NOT NULL);
INSERT INTO compat_workspace(singleton_id, selector_presentation, generation) VALUES(1, 'ABOVE', 0);
PRAGMA user_version=9;
